/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-route-data.h"
/* ca.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static CONF *extfile_conf);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static char const *crl_reasons[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int msie_hack);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int preserve);
