/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
/* asn1parse.c */
/* ca.c */
/* ciphers.c */
/* cmp.c */
/* cms.c */
/* crl.c */
/* crl2pkcs7.c */
/* dgst.c */
/* dhparam.c */
/* dsa.c */
/* dsaparam.c */
/* ec.c */
/* ecparam.c */
/* enc.c */
/* engine.c */
/* errstr.c */
/* fipsinstall.c */
/* gendsa.c */
/* genpkey.c */
/* genrsa.c */
/* info.c */
/* kdf.c */
/* list.c */
/* mac.c */
/* nseq.c */
/* ocsp.c */
/* openssl.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, extern BIO *_bsd_openssl_bio_err);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, extern BIO *_bsd_openssl_bio_in);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, extern BIO *_bsd_openssl_bio_out);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, extern char *_bsd_openssl_default_config_file);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, extern char _Linker_set_bsd_prog_openssl_begin[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, extern char _Linker_set_bsd_prog_openssl_end[]);
/* passwd.c */
/* pkcs12.c */
/* pkcs7.c */
/* pkcs8.c */
/* pkey.c */
/* pkeyparam.c */
/* pkeyutl.c */
/* prime.c */
/* progs.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, extern FUNCTION _bsd_openssl_functions[]);
/* rand.c */
/* rehash.c */
/* req.c */
/* rsa.c */
/* rsautl.c */
/* s_client.c */
/* s_server.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, extern char *_bsd_openssl_psk_key);
/* s_time.c */
/* sess_id.c */
/* smime.c */
/* speed.c */
/* spkac.c */
/* srp.c */
/* storeutl.c */
/* ts.c */
/* verify.c */
/* version.c */
/* vms_decc_init.c */
/* x509.c */
/* route.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, extern int debugonly);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, extern int verbose);
