/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-route-data.h"
/* openssl.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static char *help_argv[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int prog_inited);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static struct lhash_st_FUNCTION *ret);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static struct stack_st_tracedata *trace_data_stack);
