/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-route-data.h"
/* req.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static CONF *addext_conf);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static CONF *req_conf);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static char const *section);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int batch);
