/* generated by userspace-header-gen.py */
/* route.c */
#define debugonly _bsd_route_debugonly
#define netname _bsd_route_netname
#define printb _bsd_route_printb
#define routename _bsd_route_routename
#define verbose _bsd_route_verbose
