/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
/* route.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, extern int debugonly);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, extern int verbose);
