/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-route-data.h"
/* list.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static char const *select_name);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int verbose);
