/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-route-data.h"
/* verify.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int v_verbose);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int vflags);
