/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-route-data.h"
/* route_netlink.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static char const *nudstate[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static char const *operstate[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static struct snl_attr_parser _nla_p_link_s[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static struct snl_attr_parser _nla_p_neigh_s[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static struct snl_attr_parser _nla_p_nh_fbsd[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static struct snl_field_parser _fp_p_link_s[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static struct snl_field_parser _fp_p_neigh_s[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static struct snl_hdr_parser const *snl_all_core_parsers[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static struct snl_hdr_parser const *snl_all_route_parsers[]);
