/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-route-data.h"
/* route.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int pid);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int rtm_addrs);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int s);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int nflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int af);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int qflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int tflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int verbose);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int aflen);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int locking);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int lockrest);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int debugonly);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static struct rt_metrics rt_metrics);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static u_long rtm_inits);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static uid_t uid);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int defaultfib);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int numfibs);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static _Bool domain_initialized);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int rtm_seq);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static struct m_rtmsg m_rtmsg);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static struct fibl_head_t fibl_head);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static struct sockaddr_storage so[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static char domain[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static char rt_line[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static char net_line[]);
