/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-route-data.h"
/* s_client.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static BIO *bio_c_out);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static SSL_SESSION *psksess);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static char *keymatexportlabel);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static char *prog);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static char *psk_identity);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static char *sess_out);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int c_debug);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int c_quiet);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int c_showcerts);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int keymatexportlen);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static int saved_errno);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static struct tlsa_field tlsa_fields[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static tlsextnextprotoctx next_proto);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static uint8_t mtype);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static uint8_t selector);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static uint8_t usage);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_route, static unsigned char *data);
