/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-ping-data.h"
/* ping6.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static cap_channel_t *capdns);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static char *scmsg);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static char BBELL);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static char BSPACE);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static char const *DOT);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static char const *niqcode[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static char const *nircode[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static char rcvd_tbl6[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static char rcvd_tbl[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static int hoplimit);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static int ident);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static int interval);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static int mx_dup_ck);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static int pcp);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static int srecv);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static int ssend);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static int tclass);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static int waittime);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static int waittime6);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static long int nmissedmax);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static long int nmissedmax6);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static long int npackets);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static long int npackets6);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static long int ntransmitfailures);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static size_t DOTidx);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static size_t DOTlen);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static size_t datalen);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static size_t datalen6);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static socklen_t srclen);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static struct iovec smsgiov);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static struct msghdr smsghdr);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static struct sockaddr_in6 dst);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static struct sockaddr_in6 src);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static u_char *packet);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static u_char outpack[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static u_int8_t nonce[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static u_short naflags);
