/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
/* main.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, extern char *hostname);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, extern double tmax);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, extern double tmin);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, extern double tsum);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, extern double tsumsq);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, extern int timing);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, extern long int nrcvtimeout);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, extern long int nreceived);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, extern long int nrepeats);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, extern long int ntransmitted);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, extern sig_atomic_t volatile seeninfo);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, extern sig_atomic_t volatile seenint);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, extern u_int options);
/* ping.c */
/* ping6.c */
/* utils.c */
