/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-ping-data.h"
/* ping.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static char *shostname);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static char BBELL);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static char BSPACE);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static char const *DOT);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static char hnamebuf[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static char rcvd_tbl[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static char snamebuf[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static int datalen);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static int ident);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static int interval);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static int maxpayload);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static int phdr_len);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static int send_len);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static int srecv);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static int ssend);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static int sweepincr);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static int sweepmax);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static int sweepmin);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static int uid);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static int waittime);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static long int nmissedmax);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static long int npackets);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static long int snpackets);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static long int sntransmitted);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static sig_atomic_t volatile finish_up);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static size_t DOTidx);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static size_t DOTlen);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static struct sockaddr_in whereto);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static u_char *outpack);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static u_char icmp_type);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static u_char icmp_type_rsp);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static u_char outpackhdr[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping, static u_char packet[]);
