/* generated by userspace-header-gen.py */
/* main.c */
#define main _bsd_wlanstats_main
#define usage _bsd_wlanstats_usage
/* wlanstats.c */
#define wlanstats_new _bsd_wlanstats_wlanstats_new
#define setstatus _bsd_wlanstats_setstatus
#define setreason _bsd_wlanstats_setreason
