/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-setkey-data.h"
/* parse_wrapper.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static YYSTACKDATA yystack);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static _Bool esn);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static caddr_t p_key_auth);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static caddr_t p_key_enc);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static int p_aifamily);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static int p_aiflags);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static int p_natt_dport);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static int p_natt_fraglen);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static int p_natt_sport);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static struct addrinfo *p_natt_oai);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static struct addrinfo *p_natt_oar);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static time_t p_lt_hard);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static time_t p_lt_soft);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static u_int p_alg_auth);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static u_int p_alg_enc);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static u_int p_ext);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static u_int p_key_auth_len);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static u_int p_key_enc_len);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static u_int p_mode);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static u_int p_natt_type);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static u_int p_replay);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static u_int32_t p_reqid);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static u_int32_t p_spi);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static vchar_t p_hwif);
