/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
/* parse_wrapper.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int setkeyyychar);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int setkeyyyerrflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int setkeyyynerrs);
/* setkey.c */
/* token_wrapper.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern FILE *setkeyyyin);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern FILE *setkeyyyout);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern char *setkeyyytext);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int lineno);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int setkeyyy_flex_debug);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int setkeyyyleng);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int setkeyyylineno);
