/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-setkey-data.h"
/* setkey.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static char const *ipproto[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static char const *sastate[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static char const *satype[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static int f_all);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static int f_cmddump);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static int f_forever);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static int f_hexdump);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static int f_mode);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static int f_policy);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static int f_scope);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static int f_tflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static int f_verbose);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static int so);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static time_t thiszone);
