include config.inc

include $(RTEMS_MAKEFILE_PATH)/Makefile.inc
include $(RTEMS_CUSTOM)
include $(PROJECT_ROOT)/make/leaf.cfg
include $(PROJECT_ROOT)/make/target.cfg

CFLAGS += -ffreestanding -I . -I contrib/altq -I contrib/pf -B $(INSTALL_BASE) -w -std=gnu99

C_FILES = \
	rtems/freebsd/net/bridgestp.c \
	rtems/freebsd/net/ieee8023ad_lacp.c \
	rtems/freebsd/net/if_atmsubr.c \
	rtems/freebsd/net/if.c \
	rtems/freebsd/net/if_clone.c \
	rtems/freebsd/net/if_dead.c \
	rtems/freebsd/net/if_disc.c \
	rtems/freebsd/net/if_edsc.c \
	rtems/freebsd/net/if_ef.c \
	rtems/freebsd/net/if_enc.c \
	rtems/freebsd/net/if_epair.c \
	rtems/freebsd/net/if_faith.c \
	rtems/freebsd/net/if_fddisubr.c \
	rtems/freebsd/net/if_fwsubr.c \
	rtems/freebsd/net/if_gif.c \
	rtems/freebsd/net/if_gre.c \
	rtems/freebsd/net/if_iso88025subr.c \
	rtems/freebsd/net/if_lagg.c \
	rtems/freebsd/net/if_llatbl.c \
	rtems/freebsd/net/if_loop.c \
	rtems/freebsd/net/if_media.c \
	rtems/freebsd/net/if_mib.c \
	rtems/freebsd/net/if_spppfr.c \
	rtems/freebsd/net/if_spppsubr.c \
	rtems/freebsd/net/if_stf.c \
	rtems/freebsd/net/if_tap.c \
	rtems/freebsd/net/if_tun.c \
	rtems/freebsd/net/if_vlan.c \
	rtems/freebsd/net/pfil.c \
	rtems/freebsd/net/radix.c \
	rtems/freebsd/net/radix_mpath.c \
	rtems/freebsd/net/raw_cb.c \
	rtems/freebsd/net/raw_usrreq.c \
	rtems/freebsd/net/route.c \
	rtems/freebsd/net/rtsock.c \
	rtems/freebsd/net/slcompress.c \
	rtems/freebsd/net/zlib.c \
	rtems/freebsd/net/bpf_buffer.c \
	rtems/freebsd/net/bpf.c \
	rtems/freebsd/net/bpf_filter.c \
	rtems/freebsd/net/bpf_jitter.c \
	rtems/freebsd/net/if_arcsubr.c \
	rtems/freebsd/net/if_bridge.c \
	rtems/freebsd/net/if_ethersubr.c \
	rtems/freebsd/net/netisr.c \
	rtems/freebsd/netinet/accf_data.c \
	rtems/freebsd/netinet/accf_dns.c \
	rtems/freebsd/netinet/accf_http.c \
	rtems/freebsd/netinet/if_atm.c \
	rtems/freebsd/netinet/if_ether.c \
	rtems/freebsd/netinet/igmp.c \
	rtems/freebsd/netinet/in.c \
	rtems/freebsd/netinet/in_cksum.c \
	rtems/freebsd/netinet/in_gif.c \
	rtems/freebsd/netinet/in_mcast.c \
	rtems/freebsd/netinet/in_pcb.c \
	rtems/freebsd/netinet/in_proto.c \
	rtems/freebsd/netinet/in_rmx.c \
	rtems/freebsd/netinet/ip_carp.c \
	rtems/freebsd/netinet/ip_divert.c \
	rtems/freebsd/netinet/ip_ecn.c \
	rtems/freebsd/netinet/ip_encap.c \
	rtems/freebsd/netinet/ip_fastfwd.c \
	rtems/freebsd/netinet/ip_gre.c \
	rtems/freebsd/netinet/ip_icmp.c \
	rtems/freebsd/netinet/ip_id.c \
	rtems/freebsd/netinet/ip_input.c \
	rtems/freebsd/netinet/ip_ipsec.c \
	rtems/freebsd/netinet/ip_mroute.c \
	rtems/freebsd/netinet/ip_options.c \
	rtems/freebsd/netinet/ip_output.c \
	rtems/freebsd/netinet/raw_ip.c \
	rtems/freebsd/netinet/sctp_asconf.c \
	rtems/freebsd/netinet/sctp_auth.c \
	rtems/freebsd/netinet/sctp_bsd_addr.c \
	rtems/freebsd/netinet/sctp_cc_functions.c \
	rtems/freebsd/netinet/sctp_crc32.c \
	rtems/freebsd/netinet/sctp_indata.c \
	rtems/freebsd/netinet/sctp_input.c \
	rtems/freebsd/netinet/sctp_output.c \
	rtems/freebsd/netinet/sctp_pcb.c \
	rtems/freebsd/netinet/sctp_peeloff.c \
	rtems/freebsd/netinet/sctp_sysctl.c \
	rtems/freebsd/netinet/sctp_timer.c \
	rtems/freebsd/netinet/sctp_usrreq.c \
	rtems/freebsd/netinet/sctputil.c \
	rtems/freebsd/netinet/tcp_debug.c \
	rtems/freebsd/netinet/tcp_input.c \
	rtems/freebsd/netinet/tcp_lro.c \
	rtems/freebsd/netinet/tcp_offload.c \
	rtems/freebsd/netinet/tcp_output.c \
	rtems/freebsd/netinet/tcp_reass.c \
	rtems/freebsd/netinet/tcp_sack.c \
	rtems/freebsd/netinet/tcp_subr.c \
	rtems/freebsd/netinet/tcp_syncache.c \
	rtems/freebsd/netinet/tcp_timer.c \
	rtems/freebsd/netinet/tcp_timewait.c \
	rtems/freebsd/netinet/tcp_usrreq.c \
	rtems/freebsd/netinet/udp_usrreq.c \
	rtems/freebsd/netinet/ipfw/dn_sched_fifo.c \
	rtems/freebsd/netinet/ipfw/dn_sched_rr.c \
	rtems/freebsd/netinet/ipfw/ip_fw_log.c \
	rtems/freebsd/netinet/ipfw/dn_sched_qfq.c \
	rtems/freebsd/netinet/ipfw/dn_sched_prio.c \
	rtems/freebsd/netinet/ipfw/ip_dn_glue.c \
	rtems/freebsd/netinet/ipfw/ip_fw2.c \
	rtems/freebsd/netinet/ipfw/dn_heap.c \
	rtems/freebsd/netinet/ipfw/ip_dummynet.c \
	rtems/freebsd/netinet/ipfw/ip_fw_sockopt.c \
	rtems/freebsd/netinet/ipfw/dn_sched_wf2q.c \
	rtems/freebsd/netinet/ipfw/ip_fw_nat.c \
	rtems/freebsd/netinet/ipfw/ip_fw_pfil.c \
	rtems/freebsd/netinet/ipfw/ip_dn_io.c \
	rtems/freebsd/netinet/ipfw/ip_fw_table.c \
	rtems/freebsd/netinet/libalias/alias_dummy.c \
	rtems/freebsd/netinet/libalias/alias_pptp.c \
	rtems/freebsd/netinet/libalias/alias_smedia.c \
	rtems/freebsd/netinet/libalias/alias_mod.c \
	rtems/freebsd/netinet/libalias/alias_cuseeme.c \
	rtems/freebsd/netinet/libalias/alias_nbt.c \
	rtems/freebsd/netinet/libalias/alias_irc.c \
	rtems/freebsd/netinet/libalias/alias_util.c \
	rtems/freebsd/netinet/libalias/alias_db.c \
	rtems/freebsd/netinet/libalias/alias_ftp.c \
	rtems/freebsd/netinet/libalias/alias_proxy.c \
	rtems/freebsd/netinet/libalias/alias.c \
	rtems/freebsd/netinet/libalias/alias_skinny.c \
	rtems/freebsd/netinet/libalias/alias_sctp.c \
	rtems/freebsd/netinet6/dest6.c \
	rtems/freebsd/netinet6/frag6.c \
	rtems/freebsd/netinet6/icmp6.c \
	rtems/freebsd/netinet6/in6.c \
	rtems/freebsd/netinet6/in6_cksum.c \
	rtems/freebsd/netinet6/in6_gif.c \
	rtems/freebsd/netinet6/in6_ifattach.c \
	rtems/freebsd/netinet6/in6_mcast.c \
	rtems/freebsd/netinet6/in6_pcb.c \
	rtems/freebsd/netinet6/in6_proto.c \
	rtems/freebsd/netinet6/in6_rmx.c \
	rtems/freebsd/netinet6/in6_src.c \
	rtems/freebsd/netinet6/ip6_forward.c \
	rtems/freebsd/netinet6/ip6_id.c \
	rtems/freebsd/netinet6/ip6_input.c \
	rtems/freebsd/netinet6/ip6_ipsec.c \
	rtems/freebsd/netinet6/ip6_mroute.c \
	rtems/freebsd/netinet6/ip6_output.c \
	rtems/freebsd/netinet6/mld6.c \
	rtems/freebsd/netinet6/nd6.c \
	rtems/freebsd/netinet6/nd6_nbr.c \
	rtems/freebsd/netinet6/nd6_rtr.c \
	rtems/freebsd/netinet6/raw_ip6.c \
	rtems/freebsd/netinet6/route6.c \
	rtems/freebsd/netinet6/scope6.c \
	rtems/freebsd/netinet6/sctp6_usrreq.c \
	rtems/freebsd/netinet6/udp6_usrreq.c \
	rtems/freebsd/netipsec/ipsec_input.c \
	rtems/freebsd/netipsec/ipsec_mbuf.c \
	rtems/freebsd/netipsec/ipsec_output.c \
	rtems/freebsd/netipsec/key.c \
	rtems/freebsd/netipsec/key_debug.c \
	rtems/freebsd/netipsec/keysock.c \
	rtems/freebsd/netipsec/xform_ah.c \
	rtems/freebsd/netipsec/xform_esp.c \
	rtems/freebsd/netipsec/xform_ipcomp.c \
	rtems/freebsd/netipsec/xform_ipip.c \
	rtems/freebsd/netipsec/xform_tcp.c \
	rtems/freebsd/net80211/ieee80211_acl.c \
	rtems/freebsd/net80211/ieee80211_action.c \
	rtems/freebsd/net80211/ieee80211_adhoc.c \
	rtems/freebsd/net80211/ieee80211_ageq.c \
	rtems/freebsd/net80211/ieee80211_amrr.c \
	rtems/freebsd/net80211/ieee80211.c \
	rtems/freebsd/net80211/ieee80211_crypto.c \
	rtems/freebsd/net80211/ieee80211_crypto_ccmp.c \
	rtems/freebsd/net80211/ieee80211_crypto_none.c \
	rtems/freebsd/net80211/ieee80211_crypto_tkip.c \
	rtems/freebsd/net80211/ieee80211_crypto_wep.c \
	rtems/freebsd/net80211/ieee80211_ddb.c \
	rtems/freebsd/net80211/ieee80211_dfs.c \
	rtems/freebsd/net80211/ieee80211_freebsd.c \
	rtems/freebsd/net80211/ieee80211_hostap.c \
	rtems/freebsd/net80211/ieee80211_ht.c \
	rtems/freebsd/net80211/ieee80211_hwmp.c \
	rtems/freebsd/net80211/ieee80211_input.c \
	rtems/freebsd/net80211/ieee80211_ioctl.c \
	rtems/freebsd/net80211/ieee80211_mesh.c \
	rtems/freebsd/net80211/ieee80211_monitor.c \
	rtems/freebsd/net80211/ieee80211_node.c \
	rtems/freebsd/net80211/ieee80211_output.c \
	rtems/freebsd/net80211/ieee80211_phy.c \
	rtems/freebsd/net80211/ieee80211_power.c \
	rtems/freebsd/net80211/ieee80211_proto.c \
	rtems/freebsd/net80211/ieee80211_radiotap.c \
	rtems/freebsd/net80211/ieee80211_ratectl.c \
	rtems/freebsd/net80211/ieee80211_ratectl_none.c \
	rtems/freebsd/net80211/ieee80211_regdomain.c \
	rtems/freebsd/net80211/ieee80211_rssadapt.c \
	rtems/freebsd/net80211/ieee80211_scan.c \
	rtems/freebsd/net80211/ieee80211_scan_sta.c \
	rtems/freebsd/net80211/ieee80211_sta.c \
	rtems/freebsd/net80211/ieee80211_superg.c \
	rtems/freebsd/net80211/ieee80211_tdma.c \
	rtems/freebsd/net80211/ieee80211_wds.c \
	rtems/freebsd/net80211/ieee80211_xauth.c \
	rtems/freebsd/opencrypto/crypto.c \
	rtems/freebsd/opencrypto/deflate.c \
	rtems/freebsd/opencrypto/cryptosoft.c \
	rtems/freebsd/opencrypto/criov.c \
	rtems/freebsd/opencrypto/rmd160.c \
	rtems/freebsd/opencrypto/xform.c \
	rtems/freebsd/opencrypto/skipjack.c \
	rtems/freebsd/opencrypto/cast.c \
	rtems/freebsd/opencrypto/cryptodev.c \
	rtems/freebsd/crypto/sha1.c \
	rtems/freebsd/crypto/sha2/sha2.c \
	rtems/freebsd/crypto/rijndael/rijndael-alg-fst.c \
	rtems/freebsd/crypto/rijndael/rijndael-api.c \
	rtems/freebsd/crypto/rijndael/rijndael-api-fst.c \
	rtems/freebsd/crypto/des/des_setkey.c \
	rtems/freebsd/crypto/des/des_enc.c \
	rtems/freebsd/crypto/des/des_ecb.c \
	rtems/freebsd/crypto/blowfish/bf_enc.c \
	rtems/freebsd/crypto/blowfish/bf_skey.c \
	rtems/freebsd/crypto/blowfish/bf_ecb.c \
	rtems/freebsd/crypto/rc4/rc4.c \
	rtems/freebsd/crypto/camellia/camellia-api.c \
	rtems/freebsd/crypto/camellia/camellia.c \
	contrib/altq/rtems/freebsd/altq/altq_rmclass.c \
	contrib/altq/rtems/freebsd/altq/altq_rio.c \
	contrib/altq/rtems/freebsd/altq/altq_subr.c \
	contrib/altq/rtems/freebsd/altq/altq_cdnr.c \
	contrib/altq/rtems/freebsd/altq/altq_priq.c \
	contrib/altq/rtems/freebsd/altq/altq_cbq.c \
	contrib/altq/rtems/freebsd/altq/altq_hfsc.c \
	contrib/altq/rtems/freebsd/altq/altq_red.c \
	contrib/pf/rtems/freebsd/netinet/in4_cksum.c \
	contrib/pf/rtems/freebsd/net/pf.c \
	contrib/pf/rtems/freebsd/net/if_pflog.c \
	contrib/pf/rtems/freebsd/net/pf_subr.c \
	contrib/pf/rtems/freebsd/net/pf_ioctl.c \
	contrib/pf/rtems/freebsd/net/pf_table.c \
	contrib/pf/rtems/freebsd/net/pf_if.c \
	contrib/pf/rtems/freebsd/net/pf_osfp.c \
	contrib/pf/rtems/freebsd/net/pf_norm.c \
	contrib/pf/rtems/freebsd/net/pf_ruleset.c \
	contrib/pf/rtems/freebsd/net/if_pfsync.c \
	rtems/freebsd/dev/mii/mii.c \
	rtems/freebsd/dev/mii/mii_physubr.c \
	rtems/freebsd/dev/mii/icsphy.c \
	rtems/freebsd/rtems/rtems-bsd-cam.c \
	rtems/freebsd/rtems/rtems-bsd-nexus.c \
	rtems/freebsd/rtems/rtems-bsd-autoconf.c \
	rtems/freebsd/rtems/rtems-bsd-delay.c \
	rtems/freebsd/rtems/rtems-bsd-mutex.c \
	rtems/freebsd/rtems/rtems-bsd-thread.c \
	rtems/freebsd/rtems/rtems-bsd-condvar.c \
	rtems/freebsd/rtems/rtems-bsd-lock.c \
	rtems/freebsd/rtems/rtems-bsd-sx.c \
	rtems/freebsd/rtems/rtems-bsd-rwlock.c \
	rtems/freebsd/rtems/rtems-bsd-generic.c \
	rtems/freebsd/rtems/rtems-bsd-panic.c \
	rtems/freebsd/rtems/rtems-bsd-synch.c \
	rtems/freebsd/rtems/rtems-bsd-signal.c \
	rtems/freebsd/rtems/rtems-bsd-callout.c \
	rtems/freebsd/rtems/rtems-bsd-init.c \
	rtems/freebsd/rtems/rtems-bsd-init-with-irq.c \
	rtems/freebsd/rtems/rtems-bsd-assert.c \
	rtems/freebsd/rtems/rtems-bsd-prot.c \
	rtems/freebsd/rtems/rtems-bsd-resource.c \
	rtems/freebsd/rtems/rtems-bsd-jail.c \
	rtems/freebsd/rtems/rtems-bsd-shell.c \
	rtems/freebsd/rtems/rtems-bsd-syscalls.c \
	rtems/freebsd/rtems/rtems-bsd-malloc.c \
	rtems/freebsd/rtems/rtems-bsd-support.c \
	rtems/freebsd/rtems/rtems-bsd-bus-dma.c \
	rtems/freebsd/rtems/rtems-bsd-sysctl.c \
	rtems/freebsd/rtems/rtems-bsd-sysctlbyname.c \
	rtems/freebsd/rtems/rtems-bsd-sysctlnametomib.c \
	rtems/freebsd/rtems/rtems-bsd-uma.c \
	rtems/freebsd/local/usb_if.c \
	rtems/freebsd/local/bus_if.c \
	rtems/freebsd/local/device_if.c \
	rtems/freebsd/local/cryptodev_if.c \
	rtems/freebsd/local/miibus_if.c \
	rtems/freebsd/kern/init_main.c \
	rtems/freebsd/kern/kern_mbuf.c \
	rtems/freebsd/kern/kern_module.c \
	rtems/freebsd/kern/kern_sysctl.c \
	rtems/freebsd/kern/subr_bus.c \
	rtems/freebsd/kern/subr_kobj.c \
	rtems/freebsd/kern/uipc_mbuf.c \
	rtems/freebsd/kern/uipc_mbuf2.c \
	rtems/freebsd/kern/uipc_socket.c \
	rtems/freebsd/dev/usb/usb_busdma.c \
	rtems/freebsd/dev/usb/usb_core.c \
	rtems/freebsd/dev/usb/usb_debug.c \
	rtems/freebsd/dev/usb/usb_dev.c \
	rtems/freebsd/dev/usb/usb_device.c \
	rtems/freebsd/dev/usb/usb_dynamic.c \
	rtems/freebsd/dev/usb/usb_error.c \
	rtems/freebsd/dev/usb/usb_generic.c \
	rtems/freebsd/dev/usb/usb_handle_request.c \
	rtems/freebsd/dev/usb/usb_hid.c \
	rtems/freebsd/dev/usb/usb_hub.c \
	rtems/freebsd/dev/usb/usb_lookup.c \
	rtems/freebsd/dev/usb/usb_mbuf.c \
	rtems/freebsd/dev/usb/usb_msctest.c \
	rtems/freebsd/dev/usb/usb_parse.c \
	rtems/freebsd/dev/usb/usb_process.c \
	rtems/freebsd/dev/usb/usb_request.c \
	rtems/freebsd/dev/usb/usb_transfer.c \
	rtems/freebsd/dev/usb/usb_util.c \
	rtems/freebsd/dev/usb/quirk/usb_quirk.c \
	rtems/freebsd/dev/usb/controller/ohci.c \
	rtems/freebsd/dev/usb/controller/ehci.c \
	rtems/freebsd/dev/usb/controller/usb_controller.c \
	rtems/freebsd/dev/usb/controller/ohci_lpc3250.c \
	rtems/freebsd/cam/cam.c \
	rtems/freebsd/cam/scsi/scsi_all.c \
	rtems/freebsd/dev/usb/storage/umass.c
C_O_FILES = $(C_FILES:%.c=%.o)
C_DEP_FILES = $(C_FILES:%.c=%.dep)

LIB = libbsd.a

all: lib_usb

$(LIB): $(C_O_FILES)
	$(AR) rcu $@ $^

lib_usb:
	export PATH=$(PATH):/usr/local/gcc-4.5.2/bin ; \
	make $(LIB)

install: $(LIB)
	install -c -m 644 $(LIB) $(INSTALL_BASE)
	for i in `find . -name '*.h'` ; do install -c -m 644 -D "$$i" "$(INSTALL_BASE)/include/$$i" ; done

clean:
	rm -f -r $(PROJECT_INCLUDE)/rtems/freebsd
	rm -f $(LIB) $(C_O_FILES) $(C_DEP_FILES)

-include $(C_DEP_FILES)
