/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
/* parse.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, extern int pfctlychar);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, extern int pfctlydebug);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, extern int pfctlyerrflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, extern int pfctlynerrs);
/* pfctl_altq.c */
/* pfctl.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, extern int altqsupport);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, extern int dev);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, extern int loadopt);
/* pfctl_optimize.c */
/* pfctl_osfp.c */
/* pfctl_parser.c */
/* pfctl_qstats.c */
/* pfctl_radix.c */
/* pfctl_table.c */
/* pf_print_state.c */
