/* generated by userspace-header-gen.py */
/*
 * NOTE: MANUALLY CHANGED.
 * YACC needs a special treatment for some variables. They are commented here.
 */
#include <rtems/linkersets.h>
/* parse.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, extern int pfctlydebug);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, extern int pfctlynerrs);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, extern int pfctlyerrflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, extern int pfctlychar);
/* RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, extern YYSTYPE pfctlyval); */
/* RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, extern YYSTYPE pfctlylval); */
/* pfctl_altq.c */
/* pfctl.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, extern int loadopt);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, extern int altqsupport);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, extern int dev);
/* pfctl_optimize.c */
/* pfctl_osfp.c */
/* pfctl_parser.c */
/* pfctl_qstats.c */
/* pfctl_radix.c */
/* pfctl_table.c */
/* pf_print_state.c */
