/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-pfctl-data.h"
/* pfctl_altq.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, static char r2sbuf[][16]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, static int idx);
