/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-pfctl-data.h"
/* pfctl_table.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, static char const *stats_text[][3]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, static char const *istats_text[][2][2]);
