/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-pfctl-data.h"
/* pfctl_parser.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, static int pfctl_s);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, static int s);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, static struct hsearch_data isgroup_map);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pfctl, static struct node_host *iftab);
