/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-openssl-data.h"
/* s_server.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static BIO *bio_s_msg);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static BIO *bio_s_out);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static SSL_CTX *ctx);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static SSL_CTX *ctx2);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static SSL_SESSION *psksess);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static char **local_argv);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static char *keymatexportlabel);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static char *psk_identity);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static char const *session_id_prefix);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static char http_server_binmode);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int accept_socket);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int async);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int dtlslisten);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int early_data);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int enable_timeouts);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int keymatexportlen);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int local_argc);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int s_brief);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int s_crlf);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int s_debug);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int s_ign_eof);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int s_msg);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int s_nbio);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int s_nbio_test);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int s_quiet);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int s_tlsextdebug);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int stateless);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int use_sendfile);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int www);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static long int socket_mtu);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static simple_ssl_session *first);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static srpsrvparm srp_callback_parm);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static tlsextstatusctx tlscstatp);
