/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-openssl-data.h"
/* ec.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static OPT_PAIR conv_forms[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static OPT_PAIR param_enc[]);
