/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-openssl-data.h"
/* bf_prefix.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static BIO_METHOD *prefix_meth);
