/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-openssl-data.h"
/* ca.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static CONF *extconf);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static char const *crl_reasons[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int msie_hack);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int preserve);
