/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-openssl-data.h"
/* opt.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static OPTIONS const *opts);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static OPTIONS const *unknown);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static OPT_PAIR formats[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static char **argv);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static char *arg);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static char *dunno);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static char *flag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static char prog[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int argc);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int opt_index);
