/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-openssl-data.h"
/* fipsinstall.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static char *self_test_corrupt_desc);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static char *self_test_corrupt_type);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int quiet);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int self_test_log);
