/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-openssl-data.h"
/* passwd.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static char *passwds_static[]);
