/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-openssl-data.h"
/* ec.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static char const *asn1_encoding_options[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static char const *point_format_options[]);
