/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-openssl-data.h"
/* ecparam.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static OPT_PAIR encodings[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static OPT_PAIR forms[]);
