/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-openssl-data.h"
/* apps.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static BIO *pwdbio);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static BIO_METHOD *prefix_method);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static UI_METHOD *ui_method);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static UI_METHOD const *ui_fallback_method);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static char nmflag_set);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static long unsigned int nmflag);
