/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-openssl-data.h"
/* list.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static char const *select_name);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int verbose);
