/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
/* app_rand.c */
/* apps.c */
/* asn1pars.c */
/* bf_prefix.c */
/* ca.c */
/* ciphers.c */
/* cms.c */
/* crl2p7.c */
/* crl.c */
/* dgst.c */
/* dhparam.c */
/* dsa.c */
/* dsaparam.c */
/* ec.c */
/* ecparam.c */
/* enc.c */
/* engine.c */
/* errstr.c */
/* gendsa.c */
/* genpkey.c */
/* genrsa.c */
/* nseq.c */
/* ocsp.c */
/* openssl.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, extern BIO *bio_err);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, extern BIO *bio_in);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, extern BIO *bio_out);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, extern char *default_config_file);
/* opt.c */
/* passwd.c */
/* pkcs12.c */
/* pkcs7.c */
/* pkcs8.c */
/* pkey.c */
/* pkeyparam.c */
/* pkeyutl.c */
/* prime.c */
/* rand.c */
/* rehash.c */
/* req.c */
/* rsa.c */
/* rsautl.c */
/* s_cb.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, extern VERIFY_CB_ARGS verify_args);
/* s_client.c */
/* sess_id.c */
/* smime.c */
/* speed.c */
/* spkac.c */
/* srp.c */
/* s_server.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, extern char *psk_key);
/* s_socket.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, extern BIO_ADDR *ourpeer);
/* s_time.c */
/* storeutl.c */
/* ts.c */
/* verify.c */
/* version.c */
/* x509.c */
