/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-openssl-data.h"
/* openssl.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static FUNCTION functions[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int prog_inited);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static struct lhash_st_FUNCTION *ret);
