/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
/* asn1parse.c */
/* ca.c */
/* ciphers.c */
/* cmp.c */
/* cms.c */
/* crl.c */
/* crl2pkcs7.c */
/* dgst.c */
/* dhparam.c */
/* dsa.c */
/* dsaparam.c */
/* ec.c */
/* ecparam.c */
/* enc.c */
/* engine.c */
/* errstr.c */
/* fipsinstall.c */
/* gendsa.c */
/* genpkey.c */
/* genrsa.c */
/* info.c */
/* kdf.c */
/* list.c */
/* mac.c */
/* nseq.c */
/* ocsp.c */
/* openssl.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, extern BIO *bio_err);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, extern BIO *bio_in);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, extern BIO *bio_out);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, extern char *default_config_file);
/* passwd.c */
/* pkcs12.c */
/* pkcs7.c */
/* pkcs8.c */
/* pkey.c */
/* pkeyparam.c */
/* pkeyutl.c */
/* prime.c */
/* progs.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, extern FUNCTION functions[]);
/* rand.c */
/* rehash.c */
/* req.c */
/* rsa.c */
/* rsautl.c */
/* s_client.c */
/* s_server.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, extern char *psk_key);
/* s_time.c */
/* sess_id.c */
/* smime.c */
/* speed.c */
/* spkac.c */
/* srp.c */
/* storeutl.c */
/* ts.c */
/* verify.c */
/* version.c */
/* vms_decc_init.c */
/* x509.c */
/* lib_app_libctx.c */
/* lib_app_params.c */
/* lib_app_provider.c */
/* lib_app_rand.c */
/* lib_app_x509.c */
/* lib_apps.c */
/* lib_apps_ui.c */
/* lib_cmp_mock_srv.c */
/* lib_columns.c */
/* lib_engine.c */
/* lib_engine_loader.c */
/* lib_fmt.c */
/* lib_http_server.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, extern int acfd);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, extern int multi);
/* lib_names.c */
/* lib_opt.c */
/* lib_s_cb.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, extern VERIFY_CB_ARGS verify_args);
/* lib_s_socket.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, extern BIO_ADDR *ourpeer);
/* lib_tlssrp_depr.c */
/* lib_vms_decc_argv.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, extern char **newargv);
/* lib_vms_term_sock.c */
