/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-netstat-data.h"
/* nhgrp.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, static int wid_gw);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, static int wid_if);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, static int wid_nhidx);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, static int wid_refcnt);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, static size_t ifmap_size);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, static struct ifmap_entry *ifmap);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, static struct nhop_map global_nhop_map);
