/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
/* bpf.c */
/* if.c */
/* inet6.c */
/* inet.c */
/* ipsec.c */
/* main.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern char *interface);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern int Aflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern int Lflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern int Rflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern int Tflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern int Wflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern int aflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern int bflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern int dflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern int gflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern int hflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern int iflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern int interval);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern int live);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern int mflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern int noutputs);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern int numeric_addr);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern int numeric_port);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern int rflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern int sflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern int unit);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern int xflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern int zflag);
/* mbuf.c */
/* mroute6.c */
/* mroute.c */
/* nl_symbols.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_netstat, extern struct nlist nl[]);
/* pfkey.c */
/* route.c */
/* sctp.c */
/* unix.c */
