/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-pciconf-data.h"
/* cap.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pciconf, static int cap_level);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pciconf, static struct ecap_names_struct ecap_names[]);
