/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-pciconf-data.h"
/* err.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pciconf, static struct bit_table aer_cor[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pciconf, static struct bit_table aer_uc[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pciconf, static struct bit_table pci_status[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pciconf, static struct bit_table pcie_device_status[]);
