/* generated by userspace-header-gen.py */
/* cap.c */
#define list_caps _bsd_pciconf_list_caps
#define pci_find_cap _bsd_pciconf_pci_find_cap
#define pcie_find_cap _bsd_pciconf_pcie_find_cap
/* err.c */
#define list_errors _bsd_pciconf_list_errors
/* pciconf.c */
#define main _bsd_pciconf_main
#define print_bar _bsd_pciconf_print_bar
#define read_config _bsd_pciconf_read_config
