/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-pciconf-data.h"
/* pciconf.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pciconf, static int exitstatus);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_pciconf, static struct pci_nomatch_tab_struct pci_nomatch_tab[]);
