/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-ifmcstat-data.h"
/* ifmcstat.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifmcstat, static int af);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifmcstat, static int vflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifmcstat, static uint32_t ifindex);
