/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-tcpdump-data.h"
/* print-sip.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char const *sipcmds[]);
