/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-tcpdump-data.h"
/* print-hsrp.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char const *op_code_str[]);
