/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-tcpdump-data.h"
/* print-fr.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static struct tok const *fr_q933_ie_codesets[]);
