/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-tcpdump-data.h"
/* print-atm.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static struct tok const *oam_functype_values[]);
