/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-tcpdump-data.h"
/* print-smb.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static int request);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static int unicodestr);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static struct nbf_strings nbf_strings[]);
