/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-tcpdump-data.h"
/* print-isoclns.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static struct tok const *clnp_option_rfd_error_class[]);
