/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-tcpdump-data.h"
/* print-tcp.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static struct tcp_seq_hash tcp_seq_hash4[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static struct tcp_seq_hash6 tcp_seq_hash6[]);
