/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-tcpdump-data.h"
/* print-radius.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char const *serv_type[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char const *frm_proto[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char const *frm_routing[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char const *frm_comp[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char const *login_serv[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char const *term_action[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char const *ingress_filters[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char const *nas_port_type[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char const *acct_status[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char const *acct_auth[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char const *acct_term[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char const *tunnel_type[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char const *tunnel_medium[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char const *arap_zone[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char const *prompt[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static struct attrtype attr_type[]);
