/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-tcpdump-data.h"
/* addrtoname.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static struct hnamemem hnametable[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static struct hnamemem tporttable[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static struct hnamemem uporttable[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static struct hnamemem eprototable[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static struct hnamemem dnaddrtable[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static struct hnamemem ipxsaptable[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static struct h6namemem h6nametable[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static struct enamemem enametable[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static struct enamemem nsaptable[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static struct enamemem bytestringtable[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static struct protoidmem protoidtable[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static uint32_t f_netmask);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static uint32_t f_localnet);
