/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-tcpdump-data.h"
/* print-token.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char const *broadcast_indicator[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char const *direction[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char const *largest_frame[]);
