/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-tcpdump-data.h"
/* tcpdump.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char *zflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static int Bflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static int Cflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static int Cflag_count);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static int Dflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static int Gflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static int Gflag_count);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static int Iflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static int Jflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static int Lflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static int Qflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static int Uflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static int Wflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static int WflagChars);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static int dflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static int immediate_mode);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static int infodelay);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static int infoprint);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static int jflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static int pflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static int supports_monitor_mode);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static pcap_t *pd);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static time_t Gflag_time);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static u_int packets_captured);
