/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-tcpdump-data.h"
/* print-ptp.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char const *p_origin_ts);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char const *p_porigin_ts);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static char const *p_recv_ts);
