/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-tcpdump-data.h"
/* print-sl.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static u_int lastconn);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_tcpdump, static u_int lastlen[][256]);
