/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-ping6-data.h"
/* ping6.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static char *hostname);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static char *scmsg);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static char BBELL);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static char BSPACE);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static char DOT);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static char const *niqcode[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static char const *nircode[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static char rcvd_tbl[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static double tmax);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static double tmin);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static double tsum);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static double tsumsq);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static int hoplimit);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static int ident);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static int interval);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static int mx_dup_ck);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static int timing);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static int waittime);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static long int nmissedmax);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static long int npackets);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static long int nrcvtimeout);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static long int nreceived);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static long int nrepeats);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static long int ntransmitted);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static sig_atomic_t volatile seenint);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static size_t datalen);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static socklen_t srclen);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static struct iovec smsgiov);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static struct msghdr smsghdr);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static struct sockaddr_in6 dst);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static struct sockaddr_in6 src);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static u_char *packet);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static u_char outpack[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static u_int8_t nonce[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ping6, static u_short naflags);
