#
#  $Id$
#

include ../config.inc

include $(RTEMS_MAKEFILE_PATH)/Makefile.inc
include $(RTEMS_CUSTOM)
include $(RTEMS_SHARE)/make/directory.cfg

# servers
SUBDIRS  = mghttpd
SUBDIRS += telnetd
SUBDIRS += ftpd
# client services
SUBDIRS += ftpfs
SUBDIRS += librpc
# SUBDIRS += nfsclient
