/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-racoon-data.h"
/* prsa_par_wrapper.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static RSA *rsa_cur);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static YYSTACKDATA yystack);
