/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-racoon-data.h"
/* sha2.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct env_md_st sha2_256_md);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct env_md_st sha2_384_md);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct env_md_st sha2_512_md);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static int loading_sa);
