/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-racoon-data.h"
/* plog.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct log *logp);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static char *logfile);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct plogtags ptab[]);
