/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-racoon-data.h"
/* cftoken_wrapper.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern yy_size_t racoonyyleng);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static YY_BUFFER_STATE *yy_buffer_stack);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static char *yy_c_buf_p);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static char *yy_last_accepting_cpos);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static char yy_hold_char);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static int incstackp);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static int yy_did_buffer_switch_on_eof);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static int yy_first_time);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static int yy_init);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static int yy_more_flag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static int yy_more_len);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static int yy_start);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static size_t yy_buffer_stack_max);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static size_t yy_buffer_stack_top);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct include_stack incstack[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static yy_size_t yy_n_chars);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static yy_state_type yy_last_accepting_state);
