/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-racoon-data.h"
/* remoteconf.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static remoteconf_tailq_head_t rmtree);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static remoteconf_tailq_head_t rmtree_save);
