/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-racoon-data.h"
/* grabmyaddr.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct _myaddr_list_ configured);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct _myaddr_list_ opened);
