/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-racoon-data.h"
/* vendorid.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct vendor_id all_vendor_ids[]);
