/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-racoon-data.h"
/* strnames.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_algclass[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_attr_ipsec[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_attr_ipsec_auth[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_attr_ipsec_encmode[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_attr_ipsec_ltype[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_attr_isakmp_desc[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_attr_isakmp_enc[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_attr_isakmp_group[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_attr_isakmp_hash[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_attr_isakmp_ltype[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_attr_isakmp_method[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_direction[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_ipsec_level[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_ipsecdoi_ident[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_ipsecdoi_proto[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_ipsecdoi_trns_ah[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_ipsecdoi_trns_esp[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_ipsecdoi_trns_ipcomp[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_ipsecdoi_trns_isakmp[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_isakmp_certtype[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_isakmp_etype[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_isakmp_notify_msg[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_isakmp_nptype[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_oakley_attr[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_pfkey_satype[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct ksmap name_pfkey_type[]);
