/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-racoon-data.h"
/* nattraversal.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct _natt_ka_addrs ka_tree);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static struct sched sc_natt);
