/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-racoon-data.h"
/* backupsa.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static char *format);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static char *strmon[]);
