/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-racoon-data.h"
/* sainfo.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static sainfo_tailq_head_t sitree);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static sainfo_tailq_head_t sitree_save);
