/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-racoon-data.h"
/* pfkey.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static int (*pkrecvf[])(caddr_t *));
