/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
/* admin.c */
/* algorithm.c */
/* backupsa.c */
/* cfparse_wrapper.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern int racoonyydebug);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern int racoonyynerrs);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern int racoonyyerrflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern int racoonyychar);
/* cftoken_wrapper.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern FILE *racoonyyin);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern FILE *racoonyyout);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern int racoonyylineno);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern int racoonyy_flex_debug);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern char *racoonyytext);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern int yyerrorcount);
/* crypto_openssl.c */
/* dnssec.c */
/* evt.c */
/* genlist.c */
/* getcertsbyname.c */
/* grabmyaddr.c */
/* gssapi.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern int __gssapi_dUmMy);
/* handler.c */
/* ipsec_doi.c */
/* isakmp_agg.c */
/* isakmp_base.c */
/* isakmp.c */
/* isakmp_frag.c */
/* isakmp_ident.c */
/* isakmp_inf.c */
/* isakmp_newg.c */
/* isakmp_quick.c */
/* localconf.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern struct localconf *lcconf);
/* logger.c */
/* main.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern int dump_config);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern int f_local);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern int vflag);
/* misc.c */
/* sha2.c */
/* nattraversal.c */
/* oakley.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern struct dhgroup dh_modp768);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern struct dhgroup dh_modp1024);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern struct dhgroup dh_modp1536);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern struct dhgroup dh_modp2048);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern struct dhgroup dh_modp3072);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern struct dhgroup dh_modp4096);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern struct dhgroup dh_modp6144);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern struct dhgroup dh_modp8192);
/* pfkey.c */
/* plog.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern char *pname);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern u_int32_t loglevel);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern int f_foreground);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern int print_location);
/* policy.c */
/* privsep.c */
/* proposal.c */
/* prsa_par_wrapper.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern int prsa_cur_lineno);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern char *prsa_cur_fname);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern struct genlist *prsa_cur_list);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern enum rsa_key_type prsa_cur_type);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern int racoonprsadebug);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern int racoonprsanerrs);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern int racoonprsaerrflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern int racoonprsachar);
/* prsa_tok_wrapper.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern FILE *racoonprsain);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern FILE *racoonprsaout);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern int racoonprsalineno);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern int racoonprsa_flex_debug);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern char *racoonprsatext);
/* remoteconf.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, extern char *script_names[]);
/* rsalist.c */
/* safefile.c */
/* sainfo.c */
/* schedule.c */
/* session.c */
/* sockmisc.c */
/* str2val.c */
/* strnames.c */
/* vendorid.c */
/* vmbuf.c */
