/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-racoon-data.h"
/* main.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static char version[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static int loading_sa);
