/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-racoon-data.h"
/* isakmp.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static int (*ph1exchange[][2][12])(struct ph1handle *, vchar_t *));
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static int (*ph2exchange[][2][11])(struct ph2handle *, vchar_t *));
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_racoon, static u_char r_ck0[]);
