/* generated by userspace-header-gen.py */
/* arp.c */
#define getaddr _bsd_arp_getaddr
#define opts _bsd_arp_opts
#define valid_type _bsd_arp_valid_type
/* arp_netlink.c */
#define delete_nl _bsd_arp_delete_nl
#define print_entries_nl _bsd_arp_print_entries_nl
#define set_nl _bsd_arp_set_nl
