/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-nuttcp-data.h"
/* nuttcp.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_nuttcp, static struct rusage ru0);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_nuttcp, static struct sigaction savesigact);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_nuttcp, static struct sigaction sigact);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_nuttcp, static struct timeval time0);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_nuttcp, static struct timeval timep);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_nuttcp, static struct timeval timepk);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_nuttcp, static struct timeval timepkr);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_nuttcp, static struct timeval timepkri);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_nuttcp, static struct timeval timerx);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_nuttcp, static struct timeval timetx);
