#
#  $Id$
#

include ../config.inc

include $(RTEMS_MAKEFILE_PATH)/Makefile.inc
include $(RTEMS_CUSTOM)
include $(RTEMS_SHARE)/make/directory.cfg

# Basic Tests
SUBDIRS  = swi01
SUBDIRS += timeout01
# USB Tests
SUBDIRS += usb01 

# Network Tests
SUBDIRS += init01
SUBDIRS += loopback01
