/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "../rtems-bsd-openssl-data.h"
/* lib_app_rand.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static char *save_rand_file);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static struct stack_st_OPENSSL_STRING *randfiles);
