/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "../rtems-bsd-openssl-data.h"
/* lib_s_cb.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static BIO *bio_keylog);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static STRINT_PAIR alert_types[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static STRINT_PAIR callback_types[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static STRINT_PAIR cert_type_list[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static STRINT_PAIR chain_flags[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static STRINT_PAIR handshakes[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static STRINT_PAIR signature_tls12_alg_list[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static STRINT_PAIR signature_tls12_hash_list[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static STRINT_PAIR signature_tls13_scheme_list[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static STRINT_PAIR ssl_versions[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int cookie_initialized);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static unsigned char cookie_secret[]);
