/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "../rtems-bsd-openssl-data.h"
/* lib_http_server.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int termsig);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int verbosity);
