/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "../rtems-bsd-openssl-data.h"
/* lib_app_libctx.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static OSSL_LIB_CTX *app_libctx);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static char const *app_propq);
