/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "../rtems-bsd-openssl-data.h"
/* lib_apps.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static BIO *pwdbio);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static char nmflag_set);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static long unsigned int nmflag);
