/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "../rtems-bsd-openssl-data.h"
/* lib_app_provider.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static int provider_option_given);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_openssl, static struct stack_st_OSSL_PROVIDER *app_providers);
