#include <machine/rtems-bsd-kernel-space.h>
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpctlscd.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
rpctlscd_null_1(void *argp, void *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, RPCTLSCD_NULL,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpctlscd_connect_1(rpctlscd_connect_arg *argp, rpctlscd_connect_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, RPCTLSCD_CONNECT,
		(xdrproc_t) xdr_rpctlscd_connect_arg, (caddr_t) argp,
		(xdrproc_t) xdr_rpctlscd_connect_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpctlscd_handlerecord_1(rpctlscd_handlerecord_arg *argp, rpctlscd_handlerecord_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, RPCTLSCD_HANDLERECORD,
		(xdrproc_t) xdr_rpctlscd_handlerecord_arg, (caddr_t) argp,
		(xdrproc_t) xdr_rpctlscd_handlerecord_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpctlscd_disconnect_1(rpctlscd_disconnect_arg *argp, rpctlscd_disconnect_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, RPCTLSCD_DISCONNECT,
		(xdrproc_t) xdr_rpctlscd_disconnect_arg, (caddr_t) argp,
		(xdrproc_t) xdr_rpctlscd_disconnect_res, (caddr_t) clnt_res,
		TIMEOUT));
}
