#include <machine/rtems-bsd-kernel-space.h>
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpctlscd.h"

bool_t
xdr_rpctlscd_connect_arg(XDR *xdrs, rpctlscd_connect_arg *objp)
{

	if (!xdr_array(xdrs, (char **)&objp->certname.certname_val, (u_int *) &objp->certname.certname_len, ~0,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpctlscd_connect_res(XDR *xdrs, rpctlscd_connect_res *objp)
{

	if (!xdr_uint32_t(xdrs, &objp->reterr))
		return (FALSE);
	if (!xdr_uint64_t(xdrs, &objp->sec))
		return (FALSE);
	if (!xdr_uint64_t(xdrs, &objp->usec))
		return (FALSE);
	if (!xdr_uint64_t(xdrs, &objp->ssl))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpctlscd_handlerecord_arg(XDR *xdrs, rpctlscd_handlerecord_arg *objp)
{

	if (!xdr_uint64_t(xdrs, &objp->sec))
		return (FALSE);
	if (!xdr_uint64_t(xdrs, &objp->usec))
		return (FALSE);
	if (!xdr_uint64_t(xdrs, &objp->ssl))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpctlscd_handlerecord_res(XDR *xdrs, rpctlscd_handlerecord_res *objp)
{

	if (!xdr_uint32_t(xdrs, &objp->reterr))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpctlscd_disconnect_arg(XDR *xdrs, rpctlscd_disconnect_arg *objp)
{

	if (!xdr_uint64_t(xdrs, &objp->sec))
		return (FALSE);
	if (!xdr_uint64_t(xdrs, &objp->usec))
		return (FALSE);
	if (!xdr_uint64_t(xdrs, &objp->ssl))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpctlscd_disconnect_res(XDR *xdrs, rpctlscd_disconnect_res *objp)
{

	if (!xdr_uint32_t(xdrs, &objp->reterr))
		return (FALSE);
	return (TRUE);
}
