#include <machine/rtems-bsd-kernel-space.h>
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpctlssd.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
rpctlssd_null_1(void *argp, void *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, RPCTLSSD_NULL,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpctlssd_connect_1(void *argp, rpctlssd_connect_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, RPCTLSSD_CONNECT,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_rpctlssd_connect_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpctlssd_handlerecord_1(rpctlssd_handlerecord_arg *argp, rpctlssd_handlerecord_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, RPCTLSSD_HANDLERECORD,
		(xdrproc_t) xdr_rpctlssd_handlerecord_arg, (caddr_t) argp,
		(xdrproc_t) xdr_rpctlssd_handlerecord_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpctlssd_disconnect_1(rpctlssd_disconnect_arg *argp, rpctlssd_disconnect_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, RPCTLSSD_DISCONNECT,
		(xdrproc_t) xdr_rpctlssd_disconnect_arg, (caddr_t) argp,
		(xdrproc_t) xdr_rpctlssd_disconnect_res, (caddr_t) clnt_res,
		TIMEOUT));
}
