/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCTLSSD_H_RPCGEN
#define	_RPCTLSSD_H_RPCGEN

#include <rpc/rpc.h>

#ifdef __cplusplus
extern "C" {
#endif


struct rpctlssd_connect_res {
	uint32_t flags;
	uint64_t sec;
	uint64_t usec;
	uint64_t ssl;
	uint32_t uid;
	struct {
		u_int gid_len;
		uint32_t *gid_val;
	} gid;
};
typedef struct rpctlssd_connect_res rpctlssd_connect_res;

struct rpctlssd_handlerecord_arg {
	uint64_t sec;
	uint64_t usec;
	uint64_t ssl;
};
typedef struct rpctlssd_handlerecord_arg rpctlssd_handlerecord_arg;

struct rpctlssd_handlerecord_res {
	uint32_t reterr;
};
typedef struct rpctlssd_handlerecord_res rpctlssd_handlerecord_res;

struct rpctlssd_disconnect_arg {
	uint64_t sec;
	uint64_t usec;
	uint64_t ssl;
};
typedef struct rpctlssd_disconnect_arg rpctlssd_disconnect_arg;

struct rpctlssd_disconnect_res {
	uint32_t reterr;
};
typedef struct rpctlssd_disconnect_res rpctlssd_disconnect_res;

#define	RPCTLSSD ((unsigned long)(0x40677375))
#define	RPCTLSSDVERS ((unsigned long)(1))

extern  void rpctlssd_1(struct svc_req *rqstp, SVCXPRT *transp);
#define	RPCTLSSD_NULL ((unsigned long)(0))
extern  enum clnt_stat rpctlssd_null_1(void *, void *, CLIENT *);
extern  bool_t rpctlssd_null_1_svc(void *, void *, struct svc_req *);
#define	RPCTLSSD_CONNECT ((unsigned long)(1))
extern  enum clnt_stat rpctlssd_connect_1(void *, rpctlssd_connect_res *, CLIENT *);
extern  bool_t rpctlssd_connect_1_svc(void *, rpctlssd_connect_res *, struct svc_req *);
#define	RPCTLSSD_HANDLERECORD ((unsigned long)(2))
extern  enum clnt_stat rpctlssd_handlerecord_1(rpctlssd_handlerecord_arg *, rpctlssd_handlerecord_res *, CLIENT *);
extern  bool_t rpctlssd_handlerecord_1_svc(rpctlssd_handlerecord_arg *, rpctlssd_handlerecord_res *, struct svc_req *);
#define	RPCTLSSD_DISCONNECT ((unsigned long)(3))
extern  enum clnt_stat rpctlssd_disconnect_1(rpctlssd_disconnect_arg *, rpctlssd_disconnect_res *, CLIENT *);
extern  bool_t rpctlssd_disconnect_1_svc(rpctlssd_disconnect_arg *, rpctlssd_disconnect_res *, struct svc_req *);
extern int rpctlssd_1_freeresult(SVCXPRT *, xdrproc_t, caddr_t);

/* the xdr functions */
extern  bool_t xdr_rpctlssd_connect_res(XDR *, rpctlssd_connect_res*);
extern  bool_t xdr_rpctlssd_handlerecord_arg(XDR *, rpctlssd_handlerecord_arg*);
extern  bool_t xdr_rpctlssd_handlerecord_res(XDR *, rpctlssd_handlerecord_res*);
extern  bool_t xdr_rpctlssd_disconnect_arg(XDR *, rpctlssd_disconnect_arg*);
extern  bool_t xdr_rpctlssd_disconnect_res(XDR *, rpctlssd_disconnect_res*);

#ifdef __cplusplus
}
#endif

#endif /* !_RPCTLSSD_H_RPCGEN */
