/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
/* parse_wrapper.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int setkeyyychar);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int setkeyyydebug);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int setkeyyyerrflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int setkeyyynerrs);
/* setkey.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int exit_now);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int f_all);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int f_cmddump);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int f_debug);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int f_forever);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int f_hexdump);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int f_mode);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int f_notreally);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int f_policy);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int f_rfcmode);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int f_rkwarn);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int f_tflag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int f_verbose);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int f_withports);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int last_msg_type);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int lineno);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int so);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern u_char m_buf[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern u_int m_len);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern u_int32_t last_priority);
/* token_wrapper.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern FILE *setkeyyyin);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern FILE *setkeyyyout);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern char *setkeyyytext);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int setkeyyy_flex_debug);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern int setkeyyylineno);
