/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-setkey-data.h"
/* parse_wrapper.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static YYSTACKDATA yystack);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static char const *p_key_auth);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static char const *p_key_enc);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static int p_aifamily);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static int p_aiflags);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static size_t p_lb_hard);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static size_t p_lb_soft);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static struct addrinfo *p_natt_oa);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static struct security_ctx sec_ctx);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static time_t p_lt_hard);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static time_t p_lt_soft);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static u_int p_alg_auth);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static u_int p_alg_enc);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static u_int p_ext);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static u_int p_key_auth_len);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static u_int p_key_enc_len);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static u_int p_mode);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static u_int p_natt_type);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static u_int p_replay);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static u_int32_t p_reqid);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static u_int32_t p_spi);
