/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-setkey-data.h"
/* token_wrapper.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static size_t yy_buffer_stack_top);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static size_t yy_buffer_stack_max);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static YY_BUFFER_STATE *yy_buffer_stack);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static char yy_hold_char);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static yy_size_t yy_n_chars);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, extern yy_size_t setkeyyyleng);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static char *yy_c_buf_p);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static int yy_init);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static int yy_start);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static int yy_did_buffer_switch_on_eof);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static yy_state_type yy_last_accepting_state);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static char *yy_last_accepting_cpos);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static int yy_more_flag);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_setkey, static int yy_more_len);
