/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
/* af_inet.c */
/* af_inet6.c */
/* af_link.c */
/* af_nd6.c */
/* ifbridge.c */
/* ifclone.c */
/* ifconfig.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern char *f_addr);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern char *f_ether);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern char *f_inet);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern char *f_inet6);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern ifconfig_handle_t *lifh);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern int exit_code);
/* ifconfig_netlink.c */
/* ifgif.c */
/* ifgre.c */
/* ifgroup.c */
/* ifieee80211.c */
/* iflagg.c */
/* ifmac.c */
/* ifmedia.c */
/* ifpfsync.c */
/* ifvlan.c */
/* sfp.c */
