/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-ifconfig-data.h"
/* ifieee80211.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, static char const *modename[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, static char spacer);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, static int col);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, static int gotcurchan);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, static int gothtconf);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, static int gotregdomain);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, static int gotroam);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, static int gottxparams);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, static int gotvhtconf);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, static int htconf);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, static int vhtconf);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, static struct afswtch af_ieee80211);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, static struct cmd ieee80211_cmds[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, static struct ieee80211_channel curchan);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, static struct ieee80211_clone_params params);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, static struct ieee80211_regdomain regdomain);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, static struct ieee80211_roamparams_req roamparams);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, static struct ieee80211_txparams_req txparams);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, static struct ieee80211req_chaninfo *chaninfo);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, static struct ifmediareq *ifmr);
