/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
/* af_inet6.c */
/* af_inet.c */
/* af_link.c */
/* af_nd6.c */
/* ifbridge.c */
/* ifclone.c */
/* ifconfig.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern struct ifreq ifr);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern char name[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern char *descr);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern size_t descrlen);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern int setaddr);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern int setmask);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern int doalias);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern int clearaddr);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern int newaddr);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern int verbose);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern int noload);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern int printifname);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern int supmedia);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern int printkeys);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern char *f_inet);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern char *f_inet6);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern char *f_ether);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern char *f_addr);
/* ifgif.c */
/* ifgre.c */
/* ifgroup.c */
/* ifieee80211.c */
/* iflagg.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern char lacpbuf[]);
/* ifmac.c */
/* ifmedia.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern struct ifmedia_description ifm_subtype_ieee80211_mode_descriptions[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_ifconfig, extern struct ifmedia_description ifm_subtype_ieee80211_mode_aliases[]);
/* ifpfsync.c */
/* ifvlan.c */
/* sfp.c */
